services:
  notification-service:
    build: 
      context: .
      target: production
    environment:
      - PORT=3002
      - NODE_ENV=production
       - RABBITMQ_URL=${RABBITMQ_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=587
      - MAIL_SECURE=false
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
      - LOG_LEVEL=info