services:
  api-gateway:
    build:
      context: .
    image: api_gateway_image:1.0
    container_name: api_gateway
    ports:
      - "3000:3000"
    networks:
      - gateway-network
    environment:
      - PORT=3000

networks:
  gateway-network:
    driver: bridge