# Extend the base configuration file
services:
  # --- API Gateway Production Overrides ---
  api-gateway:
    # Use the final production target in the Dockerfile
    build:
      target: production
    environment:
      - NODE_ENV=production
      # References secrets from the host machine or .env file
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    # Re-enable the robust healthcheck
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    # Add resource management
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # --- Auth Service Production Overrides ---
  auth-service:
    build: 
      target: production
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - PORT=3001
      # References secrets from the host machine or .env file
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["npm", "run", "start"] # The final production command

  # --- Auth Migration Overrides ---
  auth-migrate:
    build:
      target: production
      args:
        - NODE_ENV=production

  # --- Database Production Overrides ---
  auth-db:
    environment:
      # References secrets from the host machine or .env file
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
