services:
  product-service:
    build: 
      target: production
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_IP=${POSTGRES_IP}
      - PORT=3001
      - REDIS_URL=${REDIS_URL}
    command: ["npm", "run", "start"]
  
  auth-db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    