services:
  auth-service:
    build:
      context: .
    image: auth_service_image:1.0
    container_name: auth_service
    ports:
      - "3001:3001"
    networks:
      - auth-net
    depends_on:
      auth-migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/v1/auth/health', (r) => {if(r.statusCode !== 200) throw new Error()})"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - auth-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db}"]
      interval: 5s
      timeout: 10s
      retries: 5

  auth-migrate:
    build: 
      context: .
      args:
        - NODE_ENV=development
      target: builder
    command: ["npm", "run", "db:push"]
    networks:
      - auth-net
    depends_on:
      auth-db: 
        condition: service_healthy
    
  redis:
    image: redis
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge
