services:
  auth-service:
    build: 
      context: .
      args:
        - NODE_ENV=development
      target: builder
    environment:
      PORT: 3001
      NODE_ENV: development
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: auth_db
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - /app/node_modules
    command: ["npm", "run", "dev"]

  db:
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: auth_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: