services:
  auth-service:
    build: 
      context: .
      args:
        - NODE_ENV=production
      target: production
    environment:
      - NODE_ENV=production
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=3001
    command: ["npm", "run", "start"]

  auth-db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
