services:
  auth_service:
    build: 
      context: .
      args:
        - NODE_ENV=production
      target: production
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
